#!/bin/dash

# init
index_folder=".shrug/index"

# error: shrug repository does not exist
if [ ! -e ".shrug" ]
then
    echo "shrug-add: error: no .shrug directory containing shrug repository exists"
    exit 1
fi

# error: missing arguements
if [ $# -eq 0 ]
then
    echo "usage: shrug-add <filenames>"
    exit 1
fi

# loop through <filenames>
for file in $@
do
    # error: invalid file name
    echo $file | grep -P -q "^[a-zA-Z0-9]+[.|-|_]*"
    if [ $? -ne 0 ]
    then
        echo "shrug-add: error: invalid filename '$file'"
        exit 1
    fi

    # error: file does not exist
    if [ ! -e $file -a ! -e "$index_folder/$file" ]
    then
        echo "shrug-add: error: can not open '$file'"
        exit 1
    fi

    # rm file from index if it no-longer exist in current directory
    if [ ! -e $file -a -e "$index_folder/$file" ]
    then
        rm "$index_folder/$file"
    else # add file to index
        cp $file $index_folder
    fi
done

#TODO:(handle duplicated input arguments)
# touch a b c
# shrug-add a b a c b
# a b c added to index with no error (no message)