#!/bin/dash

#init
branch="master"
commit_number=""
file=""
folder=""
file_path=""
is_commit_number_exist="false"
is_in_index_folder="false"

# error: shrug repository does not exist
if [ ! -e ".shrug" ]
then
    echo "shrug-show: error: no .shrug directory containing shrug repository exists"
    exit 1
fi

# error: number of arguements is not 1
if [ $# -ne 1 ]
then
    echo "usage: shrug-show <commit>:<filename>"
    exit 1
fi

# error: invalid input format
echo $1 | grep -P -q ":"
if [ $? -ne 0 ]
then
    echo "shrug-show: error: invalid object $1"
    exit 1
fi

# get commit number and file name
commit_number=`echo $1 | cut -d":" -f1`
file=`echo $1 | cut -d":" -f2`

if [ -z $commit_number ]
then
    folder=".shrug/index"
    is_in_index_folder="true"
else
    folder=".shrug/repo/$branch/$commit_number"
fi

# error: invalid file name format
echo $file | grep -P -q "^[a-zA-Z0-9]+[.|-|_]*"
if [ $? -ne 0 ]
then
    echo "shrug-show: error: invalid filename '$file'"
    exit 1
fi

# error: commit number does not exist
for available_commit_number in `cat .shrug/repo/shrug.log | cut -d" " -f1`
do
    # check commit number is numeric 
    echo $commit_number | grep -P -q "^[0-9]+$"
    if [ $? -ne 0 ]
    then
        break
    fi

    # check commit number exist in log
    if [ $commit_number -eq $available_commit_number ]
    then
        is_commit_number_exist="true"
        break
    fi
done

if [ $is_commit_number_exist = "false" -a $is_in_index_folder = "false" ]
then
    echo "shrug-show: error: unknown commit '$commit_number'"
    exit 1
fi

# error: file does not exist in the target folder
file_path="$folder/$file"
if [ ! -e $file_path ]
then
    if [ $is_in_index_folder = "true" ] # no commit number, in the index folder
    then
        echo "shrug-show: error: '$file' not found in index"
        exit 1
    else # has commit number, in the repo folder
        echo "shrug-show: error: '$file' not found in commit $commit_number"
        exit 1
    fi
fi

cat $file_path