#!/bin/dash

#init
index_folder=".shrug/index"
log_file=".shrug/repo/shrug.log"
last_commit_number=0
last_commit_folder=""
commit_branch="master"
temp_status_print_file=".shrug/repo/status_print.temp"
files=$@

# error: shrug repository does not exist
if [ ! -e ".shrug" ]
then
    echo "shrug-status: error: no .shrug directory containing shrug repository exists"
    exit 1
fi

# error: repository does not have any commits yet
if [ -z "`cat .shrug/repo/shrug.log`" ]
then
    echo "shrug-status: error: your repository does not have any commits yet"
    exit 1
fi

# scan files from current directory
touch $temp_status_print_file
for file in `ls`
do
    echo $file >> $temp_status_print_file
done

# scan files from index
for file in `ls $index_folder`
do
    echo $file >> $temp_status_print_file
done

# scan files from last commit
last_commit_number=`cat $log_file | tail -n1 | cut -d" " -f1`
last_commit_folder=".shrug/repo/$commit_branch/$last_commit_number"
for file in `ls $last_commit_folder`
do
    echo $file >> $temp_status_print_file
done

# check if there is any file name that needs to display status, if not, exit
if [ -z "`cat $temp_status_print_file`" ]
then
    exit 0
fi

# remove duplicated file names
files=`sort $temp_status_print_file | uniq`
rm $temp_status_print_file

# get status for each file
for file in $files
do
    is_file_exist_in_cur_dir="false"
    is_file_exist_in_index="false"
    is_file_exist_in_last_commit="false"

    is_file_diff_cur_dir_vs_last_commit="false"
    is_file_diff_cur_dir_vs_index="false"
    is_file_diff_index_vs_last_commit="false"
    
    # check if file exist in current dir
    if [ -e $file ]
    then
        is_file_exist_in_cur_dir="true"
    fi

    # check if file exist in index
    if [ -e "$index_folder/$file" ]
    then
        is_file_exist_in_index="true"
    fi

    # check if file exist in last commit
    if [ -e "$last_commit_folder/$file" ]
    then
        is_file_exist_in_last_commit="true"
    fi

    # check file difference between current directory and last commit folder
    if [ $is_file_exist_in_cur_dir = "true" -a $is_file_exist_in_last_commit = "true" ]
    then
        if ! cmp -s "$file" "$last_commit_folder/$file"
        then
            is_file_diff_cur_dir_vs_last_commit="true"
        fi
    fi

    # check file difference between current directory and index folder
    if [ $is_file_exist_in_cur_dir = "true" -a $is_file_exist_in_index = "true" ]
    then
        if ! cmp -s "$file" "$index_folder/$file"
        then
            is_file_diff_cur_dir_vs_index="true"
        fi
    fi

    # check file difference between index folder and last commit folder
    if [ $is_file_exist_in_index = "true" -a $is_file_exist_in_last_commit = "true" ]
    then
        if ! cmp -s "$index_folder/$file" "$last_commit_folder/$file"
        then
            is_file_diff_index_vs_last_commit="true"
        fi
    fi

    # status: same as repo
    # what is file changed? file exist in last commit, and file was changed either in index or in current directory
    is_file_changed="false"
    if [ $is_file_exist_in_cur_dir = "true" \
        -a $is_file_exist_in_index = "true" \
        -a $is_file_exist_in_last_commit = "true" \
        -a $is_file_diff_cur_dir_vs_index = "false" \
        -a $is_file_diff_cur_dir_vs_last_commit = "false" \
        -a $is_file_diff_index_vs_last_commit = "false" ]
    then
        echo "$file - same as repo"
        continue
    else
        if [ $is_file_exist_in_last_commit = "true" ]
        then
            is_file_changed="true"
        fi
    fi

    # check if file is added to index
    is_file_added_to_index="false"
    if [ $is_file_exist_in_index = "true" -a $is_file_exist_in_last_commit = "false" ]
    then
        is_file_added_to_index="true"
    fi

    # check if file is deleted from current directory
    is_file_deleted_from_cur_dir="false"
    if [ $is_file_exist_in_cur_dir = "false" -a $is_file_exist_in_index = "true" ]
    then
        is_file_deleted_from_cur_dir="true"
    fi

    # status: file changed, different changes staged for commit
    if [ $is_file_changed = "true" -a $is_file_diff_cur_dir_vs_index = "true" -a $is_file_diff_index_vs_last_commit = "true" ]
    then
        echo "$file - file changed, different changes staged for commit"
        continue
    fi

    # status: file changed, changes staged for commit
    if [ $is_file_changed = "true" -a $is_file_diff_cur_dir_vs_index = "false" -a $is_file_diff_index_vs_last_commit = "true" ]
    then
        echo "$file - file changed, changes staged for commit"
        continue
    fi

    # status: file changed, changes not staged for commit
    if [ $is_file_changed = "true" -a $is_file_diff_cur_dir_vs_index = "true" -a $is_file_diff_index_vs_last_commit = "false" ]
    then
        echo "$file - file changed, changes not staged for commit"
        continue
    fi

    # status: added to index, file changed
    if [ $is_file_added_to_index = "true" -a $is_file_diff_cur_dir_vs_index = "true" ]
    then
        echo "$file - added to index, file changed"
        continue
    fi

    # status: added to index, file deleted
    if [ $is_file_added_to_index = "true" -a $is_file_deleted_from_cur_dir = "true" ]
    then
        echo "$file - added to index, file deleted"
        continue
    fi   

    # status: added to index
    if [ $is_file_added_to_index = "true" ]
    then
        echo "$file - added to index"
        continue
    fi

    # status: file deleted
    if [ $is_file_deleted_from_cur_dir = "true" ]
    then
        echo "$file - file deleted"
        continue
    fi

    # status: deleted
    if [ $is_file_exist_in_cur_dir = "false" -a $is_file_exist_in_index = "false" -a $is_file_exist_in_last_commit = "true" ]
    then
        echo "$file - deleted"
        continue
    fi

    # status: untracked
    if [ $is_file_exist_in_cur_dir = "true" -a $is_file_exist_in_index = "false" ]
    then
        echo "$file - untracked"
        continue
    fi
done