#!/bin/dash

# error: number of arguement is not 0
if [ $# -ne 0 ]
then
    echo "usage: shrug-init"
    exit 1
fi

# error: .shrug folder already exist
if [ -e ".shrug" ]
then
    echo "shrug-init: error: .shrug already exists"
    exit 1
fi

# create .shrug folder
echo "Initialized empty shrug repository in .shrug"
mkdir ".shrug"

# create the sub index folder
mkdir ".shrug/index"

# create the sub repo folder
mkdir ".shrug/repo"

# create the sub sub master folder(default branch)
mkdir ".shrug/repo/master"

# create log file in the sub repo folder
touch ".shrug/repo/shrug.log"
