#!/bin/dash

#TODO:
# shrug-init
# Initialized empty shrug repository in .shrug
# shrug-add a b c
# shrug-rm a
# shrug-rm: error: your repository does not have any commits yet (this fault is above all)

#TODO:
# shrug-init
# Initialized empty shrug repository in .shrug
# shrug-add a b c
# shrug-commit -a -m "first commit"
# shrug-rm
# usage: shrug-rm [--force] [--cached] <filenames>
# shrug-rm --force
# usage: shrug-rm [--force] [--cached] <filenames>

#TODO:
# shrug-init
# Initialized empty shrug repository in .shrug
# shrug-add a b c
# shrug-commit -a -m "first commit"
# shrug-rm a
# a is removed from both current dir and index (no message)
# shrug-rm a
# shrug-rm: error: 'a' is not in the shrug repository

#TODO:
# shrug-init
# Initialized empty shrug repository in .shrug
# shrug-add a b c
# shrug-commit -a -m "first commit"
# shrug-rm --cached b
# b is removed from index only (no message)
# shrug-rm --cached b
# shrug-rm: error: 'b' is not in the shrug repository

#TODO:(the operated files in current dir and index are the same, then shrug-rm --force behaves like shrug-rm)
# shrug-init
# Initialized empty shrug repository in .shrug
# shrug-add a b c
# shrug-commit -a -m "first commit"
# shrug-rm --force b
# b is removed from both current dir and index (no message)

#TODO:(the operated files in the current dir is different from the one in index, then only shrug-rm would report error, shrug-rm --force would not)
# shrug-init
# Initialized empty shrug repository in .shrug
# touch a b c
# shrug-add a b c
# shrug-commit -m "first commit"
# Committed as commit 0
# echo a > a
# echo b > b
# echo c > c
# shrug-rm a
# shrug-rm: error: 'a' in repository is different to working file

# shrug-rm --cached a
# a is removed from index (no message)

# shrug-rm --force a (a exist in current but not in index)
# shrug-rm: error: 'a' is not in the shrug repository

# shrug-rm b
# shrug-rm: error: 'b' in repository is different to working file

# shrug-rm --force b
# b is removed from current dir and index (no message)

#TODO: (when --force --cached are both present, always use --force)
# shrug-init
# Initialized empty shrug repository in .shrug
# touch a b c
# shrug-add a b c
# shrug-commit -m "first commit"
# Committed as commit 0
# shrug-rm --force --cached a
# a is removed from both current dir and index (no message)

# shrug-rm --cached --force b
# b is removed from both current dir and index (no message)
