#!/bin/dash
is_format_valid="false"
is_option_force_selected="false"
is_option_cached_selected="false"
last_commit_number=0
commit_branch="master"
last_commit_folder=""
log_file=".shrug/repo/shrug.log"
index_folder=".shrug/index"
temp_rm_print_file=".shrug/repo/rm_print.temp"
file_name_pattern="^[a-zA-Z0-9]+[.|-|_]*"
files=$@

# error: shrug repository does not exist
if [ ! -e ".shrug" ]
then
    echo "shrug-rm: error: no .shrug directory containing shrug repository exists"
    exit 1
fi

# error: no commit exist
if [ -z "`cat $log_file`" ]
then
    echo "shrug-rm: error: your repository does not have any commits yet"
    exit 1
fi

# input format check
# Shrug-rm files ($# >= 1)
if [ $# -ge 1 -a $is_format_valid = "false" ]
then
    if [ $1 != "--force" -a $1 != "--cached" ]
    then
        is_format_valid="true"
    fi
fi

# Shrug-rm --cached files ($# >= 2)
# Shrug-rm --force files ($# >= 2)
if [ $# -ge 2 -a $is_format_valid = "false" ]
then
    if [ $1 = "--cached" -a $2 != "--force" ]
    then  
        is_format_valid="true"
        is_option_cached_selected="true"
    fi

    if [ $1 = "--force" -a $2 != "--cached" ]
    then
        is_format_valid="true"
        is_option_force_selected="true"
    fi
    
    if [ $is_format_valid = "true" ]
    then
        shift 1
        files=$@
    fi
fi

# Shrug-rm --force --cached files ($# >= 3)
# Shrug-rm --cached --force files ($# >= 3)
if [ $# -ge 3 -a $is_format_valid = "false" ]
then
    if [ $1 = "--force" -a $2 = "--cached" ]
    then
        is_format_valid="true"
        is_option_cached_selected="true"
        is_option_force_selected="true"
    fi

    if [ $1 = "--cached" -a $2 = "--force" ]
    then
        is_format_valid="true"
        is_option_cached_selected="true"
        is_option_force_selected="true"
    fi

    if [ $is_format_valid = "true" ]
    then
        shift 2
        files=$@
    fi
fi

# check if there is any commands in the files listed in the arguements
for file in $files
do
    echo $file | grep -P -q "^-+"
    if [ $? -eq 0 ] # match pattern found
    then
        is_format_valid="false"
        break
    fi
done

# error: input format is wrong
if [ $is_format_valid = "false" ]
then
    echo "usage: shrug-rm [--force] [--cached] <filenames>"
    exit 1
fi

# error: invalid file name
for file in $files
do
    # error: invalid file name
    echo $file | grep -P -q "^[a-zA-Z0-9]+[.|-|_]*"
    if [ $? -ne 0 ]
    then
        echo "shrug-rm: error: invalid filename '$file'"
        exit 1
    fi
done

# remove duplicated file names
touch $temp_rm_print_file
for file in $files
do
    echo $file >> $temp_rm_print_file
done
files=`sort $temp_rm_print_file | uniq`
rm $temp_rm_print_file

# only remove files in the index folder
# [--cached] with safety check
# [--force] [--cached] without safety check
if [ $is_option_cached_selected = "true" ]
then
    # error: all files must exist in index, otherwise exit and o not delete any file
    for file in $files
    do
        if [ ! -e "$index_folder/$file" ]
        then
            echo "shrug-rm: error: '$file' is not in the shrug repository"
            exit 1
        fi
    done

    # check if file in current direcory is different from the one in index, otherwise exit and do not delete any file
    if [ $is_option_force_selected = "false" ]
    then
        for file in $files
        do
            is_diff_to_last_commit="false"
            is_diff_to_cur_dir="false"

            # check 1: compare index file with last commit (cannot have staged but uncommitted files)
            last_commit_number=`cat $log_file | tail -n1 | cut -d" " -f1`
            last_commit_folder=".shrug/repo/$commit_branch/$last_commit_number"
            if ! cmp -s "$index_folder/$file" "$last_commit_folder/$file"
            then
                is_diff_to_last_commit="true"
            fi

            # chcek 2: compare content of each file (cannot have diff files in cur dir and index )
            if ! cmp -s "$file" "$index_folder/$file"
            then
                is_diff_to_cur_dir="true"
            fi

            if [ $is_diff_to_cur_dir = "true" -a $is_diff_to_last_commit = "true" ]
            then
                echo "shrug-rm: error: '$file' in index is different to both working file and repository"
                exit 1
            fi
        done
    fi

    # remove file from index folder
    for file in $files
    do
        rm "$index_folder/$file"
    done
fi

# emove from both current directory and index folder
# [] with safety check
# [--force] without safety check
if [ $is_option_cached_selected = "false" ]
then

    # error: all files must exist in both current directory and index, otherwise exit and do not delete any file
    for file in $files
    do
        if [ ! -e "$file" -o ! -e "$index_folder/$file" ]
        then
            echo "shrug-rm: error: '$file' is not in the shrug repository"
            exit 1
        fi
    done

    # [] option: check if file in current direcory is different from the one in index, otherwise exit and do not delete any file
    if [ $is_option_force_selected = "false" ]
    then
        for file in $files
        do
            is_diff_to_last_commit="false"
            is_diff_to_cur_dir="false"

            # check 1: compare index file with last commit (cannot have staged but uncommitted files)
            last_commit_number=`cat $log_file | tail -n1 | cut -d" " -f1`
            last_commit_folder=".shrug/repo/$commit_branch/$last_commit_number"
            if ! cmp -s "$index_folder/$file" "$last_commit_folder/$file"
            then
                is_diff_to_last_commit="true"
            fi

            # chcek 2: compare content of each file (cannot have diff files in cur dir and index )
            if ! cmp -s "$file" "$index_folder/$file"
            then
                is_diff_to_cur_dir="true"
            fi

            if [ $is_diff_to_cur_dir = "true" -a $is_diff_to_last_commit = "false" ]
            then
                echo "shrug-rm: error: '$file' in repository is different to working file"
                exit 1
            fi

            if [ $is_diff_to_cur_dir = "false" -a $is_diff_to_last_commit = "true" ]
            then
                echo "shrug-rm: error: '$file' has changes staged in the index"
                exit 1
            fi

            if [ $is_diff_to_cur_dir = "true" -a $is_diff_to_last_commit = "true" ]
            then
                echo "shrug-rm: error: '$file' in index is different to both working file and repository"
                exit 1
            fi
        done
    fi

    # remove file from both index and current directory
    for file in $files
    do
        rm "$file"
        rm "$index_folder/$file"
    done
fi