#!/bin/dash

# init
index_folder=".shrug/index"
temp_add_print_file=".shrug/repo/add_print.temp"
files=$@

# error: shrug repository does not exist
if [ ! -e ".shrug" ]
then
    echo "shrug-add: error: no .shrug directory containing shrug repository exists"
    exit 1
fi

# error: missing arguements
if [ $# -eq 0 ]
then
    echo "usage: shrug-add <filenames>"
    exit 1
fi

# remove duplicated file names
touch $temp_add_print_file
for file in $files
do
    echo $file >> $temp_add_print_file
done
files=`sort $temp_add_print_file | uniq`
rm $temp_add_print_file

# loop through <filenames>
for file in $files
do
    # error: invalid file name
    echo $file | grep -P -q "^[a-zA-Z0-9]+[.|-|_]*"
    if [ $? -ne 0 ]
    then
        echo "shrug-add: error: invalid filename '$file'"
        exit 1
    fi

    # error: file does not exist
    if [ ! -e $file -a ! -e "$index_folder/$file" ]
    then
        echo "shrug-add: error: can not open '$file'"
        exit 1
    fi

    # rm file from index if it no-longer exist in current directory
    if [ ! -e $file -a -e "$index_folder/$file" ]
    then
        rm "$index_folder/$file"
    else # add file to index
        cp $file $index_folder
    fi
done